(()=>{
const ENDPOINT='https://ptzurrebwksuvuakgvym.supabase.co/functions/v1/spacemail-inbox';
const ANON='sb_publishable_6Bkkj4-O_mw2YY9DGo3E2g_qnew4zZL';
const PAGE_SIZE=3;let emails=[],page=0;
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function sender(v=''){return v.replace(/<[^>]+>/g,'').replace(/^"|"$/g,'').trim()||v}
function when(v=''){const d=new Date(v);return isNaN(d)?v:d.toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}
function clean(v=''){return String(v).replace(/^BODY\[TEXT\][^}]*}\s*/i,'')}
function headers(){return {'Content-Type':'application/json','apikey':ANON,'Authorization':'Bearer '+ANON}}
function addBlessingToHandledBy(){const sel=document.getElementById('outBy');if(!sel)return false;const name='Blessing Chisom Eze';if(![...sel.options].some(o=>o.value===name||o.textContent.trim()===name)){const o=document.createElement('option');o.value=name;o.textContent=name;sel.appendChild(o)}return true}
function ensure(){const out=document.getElementById('outreach');if(!out||document.getElementById('vyraInbox'))return false;addBlessingToHandledBy();const box=document.createElement('section');box.className='panel';box.id='vyraInbox';box.innerHTML=`<div style="display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap"><div><span class="kicker">HELLO@VYRACOLLECTIVE.ORG</span><h2 style="margin:6px 0">Inbox</h2><div class="muted" id="inboxStatus">Loading inbox…</div></div><button class="btn secondary" id="inboxRefresh">Refresh Inbox</button></div><div id="inboxList" style="display:grid;gap:10px;margin-top:18px"></div><div id="inboxPager" style="display:flex;align-items:center;justify-content:center;gap:12px;margin-top:16px"></div>`;const preview=out.querySelector('.previewbox');preview?out.insertBefore(box,preview):out.appendChild(box);document.getElementById('inboxRefresh').onclick=()=>load(true);load(true);return true}
function render(){const list=document.getElementById('inboxList'),pager=document.getElementById('inboxPager'),status=document.getElementById('inboxStatus');if(!list||!pager||!status)return;emails.sort((a,b)=>(Date.parse(b.date)||Number(b.uid)||0)-(Date.parse(a.date)||Number(a.uid)||0));const pages=Math.max(1,Math.ceil(emails.length/PAGE_SIZE));if(page>=pages)page=pages-1;status.textContent=`${emails.length} latest email${emails.length===1?'':'s'} • newest first`;if(!emails.length){list.innerHTML='<div class="notice">No emails found.</div>';pager.innerHTML='';return}const start=page*PAGE_SIZE,slice=emails.slice(start,start+PAGE_SIZE);list.innerHTML=slice.map((e,j)=>{const i=start+j;return `<article style="border:1px solid var(--line);border-radius:14px;background:#ffffff08;overflow:hidden"><div style="display:flex;align-items:stretch"><button type="button" data-mail="${i}" style="flex:1;border:0;background:transparent;color:inherit;text-align:left;padding:15px;cursor:pointer"><div style="display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap"><strong>${esc(sender(e.from))}</strong><small class="muted">${esc(when(e.date))}</small></div><div style="font-weight:800;margin:6px 0">${esc(e.subject||'(No subject)')}</div><div class="muted" style="font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(clean(e.preview||''))}</div></button><button type="button" data-delete="${esc(e.uid)}" title="Delete email" style="border:0;border-left:1px solid var(--line);background:transparent;color:#d66;padding:0 16px;cursor:pointer;font-weight:800">Delete</button></div><div id="mail-${i}" style="display:none;padding:0 15px 15px"><div class="notice" style="margin:0;white-space:pre-wrap">${esc(clean(e.preview||'No message preview available.'))}</div></div></article>`}).join('');list.querySelectorAll('[data-mail]').forEach(b=>b.onclick=()=>{const p=document.getElementById('mail-'+b.dataset.mail);p.style.display=p.style.display==='none'?'block':'none'});list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeMail(b.dataset.delete));pager.innerHTML=`<button class="btn secondary" id="inboxPrev" ${page===0?'disabled':''}>Previous</button><span class="muted">Page ${page+1} of ${pages}</span><button class="btn secondary" id="inboxNext" ${page>=pages-1?'disabled':''}>Next</button>`;document.getElementById('inboxPrev').onclick=()=>{if(page>0){page--;render()}};document.getElementById('inboxNext').onclick=()=>{if(page<pages-1){page++;render()}}}
async function load(reset=false){const list=document.getElementById('inboxList'),status=document.getElementById('inboxStatus');if(!list||!status)return;if(reset)page=0;status.textContent='Refreshing inbox…';list.innerHTML='<div class="notice">Loading emails…</div>';try{const r=await fetch(ENDPOINT,{method:'POST',headers:headers(),body:'{}'});const data=await r.json();if(!r.ok||!data.success)throw new Error(data.error||'Unable to load inbox');emails=Array.isArray(data.emails)?data.emails:[];render()}catch(e){status.textContent='Inbox unavailable';list.innerHTML='<div class="notice">Could not load inbox: '+esc(e.message)+'</div>'}}
async function removeMail(uid){if(!confirm('Delete this email from the VYRA/Spacemail inbox?'))return;try{const r=await fetch(ENDPOINT,{method:'POST',headers:headers(),body:JSON.stringify({action:'delete',uid})});const data=await r.json();if(!r.ok||!data.success)throw new Error(data.error||'Could not delete email');emails=emails.filter(e=>String(e.uid)!==String(uid));render()}catch(e){alert('Delete failed: '+e.message)}}
addBlessingToHandledBy();
if(!ensure()){const t=setInterval(()=>{addBlessingToHandledBy();if(ensure())clearInterval(t)},400)}
})();