(()=>{
const ENDPOINT='https://ptzurrebwksuvuakgvym.supabase.co/functions/v1/spacemail-inbox';
const ANON='sb_publishable_6Bkkj4-O_mw2YY9DGo3E2g_qnew4zZL';
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function sender(v=''){return v.replace(/<[^>]+>/g,'').replace(/^"|"$/g,'').trim()||v}
function when(v=''){const d=new Date(v);return isNaN(d)?v:d.toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}
function ensure(){const out=document.getElementById('outreach');if(!out||document.getElementById('vyraInbox'))return false;const box=document.createElement('section');box.className='panel';box.id='vyraInbox';box.innerHTML=`<div style="display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap"><div><span class="kicker">HELLO@VYRACOLLECTIVE.ORG</span><h2 style="margin:6px 0">Inbox</h2><div class="muted" id="inboxStatus">Loading incoming replies…</div></div><button class="btn secondary" id="inboxRefresh">Refresh Inbox</button></div><div id="inboxList" style="display:grid;gap:10px;margin-top:18px"></div>`;const preview=out.querySelector('.previewbox');preview?out.insertBefore(box,preview):out.appendChild(box);document.getElementById('inboxRefresh').onclick=load;load();return true}
async function load(){const list=document.getElementById('inboxList'),status=document.getElementById('inboxStatus');if(!list||!status)return;status.textContent='Refreshing inbox…';list.innerHTML='<div class="notice">Loading emails…</div>';try{const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','apikey':ANON,'Authorization':'Bearer '+ANON},body:'{}'});const data=await r.json();if(!r.ok||!data.success)throw new Error(data.error||'Unable to load inbox');const emails=Array.isArray(data.emails)?data.emails:[];status.textContent=`${emails.length} latest email${emails.length===1?'':'s'}`;if(!emails.length){list.innerHTML='<div class="notice">No emails found.</div>';return}list.innerHTML=emails.map((e,i)=>`<article style="border:1px solid var(--line);border-radius:14px;background:#ffffff08;overflow:hidden"><button type="button" data-mail="${i}" style="width:100%;border:0;background:transparent;color:inherit;text-align:left;padding:15px;cursor:pointer"><div style="display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap"><strong>${esc(sender(e.from))}</strong><small class="muted">${esc(when(e.date))}</small></div><div style="font-weight:800;margin:6px 0">${esc(e.subject||'(No subject)')}</div><div class="muted" style="font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc((e.preview||'').replace(/^BODY\[TEXT\][^}]*}\s*/i,''))}</div></button><div id="mail-${i}" style="display:none;padding:0 15px 15px"><div class="notice" style="margin:0;white-space:pre-wrap">${esc((e.preview||'No message preview available.').replace(/^BODY\[TEXT\][^}]*}\s*/i,''))}</div></div></article>`).join('');list.querySelectorAll('[data-mail]').forEach(b=>b.onclick=()=>{const p=document.getElementById('mail-'+b.dataset.mail);p.style.display=p.style.display==='none'?'block':'none'})}catch(e){status.textContent='Inbox unavailable';list.innerHTML='<div class="notice">Could not load inbox: '+esc(e.message)+'</div>'}}
if(!ensure()){const t=setInterval(()=>{if(ensure())clearInterval(t)},400)}
})();